language: python
addons:
  apt:
    packages:
      - python-wxgtk2.8
      - python-wxtools
      - wx2.8-doc
      - wx2.8-examples
      - wx2.8-headers
      - wx2.8-i18n
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - python setup.py install --user
script:
  - easy_selenium_cli.py easyselenium/tests/ -b phantomjs
