sudo: required
dist: trusty
language: python
addons:
  apt:
    packages:
      - python-wxgtk2.8
      - python-wxtools
      - wx2.8-doc
      - wx2.8-examples
      - wx2.8-headers
      - wx2.8-i18n
python:
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y chromium-chromedriver
install:
  - pip install -U -r requirements.txt
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
script:
  - easyselenium/scripts/easy_selenium_cli.py --with-path /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode --logging-level=INFO -b gc
