language: python
addons:
  apt:
    packages:
      - python-wxgtk2.8
      - python-wxtools
      - wx2.8-doc
      - wx2.8-examples
      - wx2.8-headers
      - wx2.8-i18n
python:
  - "2.7"
install:
  - pip install selenium
  - pip install nose-pathmunge
  - pip install nose-htmloutput
script:
  - easyselenium/scripts/easy_selenium_cli.py --with-path . -w easyselenium/tests/ -b phantomjs
