language: python
addons:
  apt:
    packages:
      - python-wxgtk2.8
      - python-wxtools
      - wx2.8-doc
      - wx2.8-examples
      - wx2.8-headers
      - wx2.8-i18n
  firefox: "49.0"
python:
  - "2.7"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.15.0-linux64.tar.gz
  - rm geckodriver-v0.15.0-linux64.tar.gz
  - mv geckodriver ~/
install:
  - pip install -r requirements.txt
script:
  - easyselenium/scripts/easy_selenium_cli.py -b ff easyselenium/tests/browser_test.py
