sudo: required
dist: trusty
language: python
python:
  - '2.7'
  - '3.6'
before_install:
  - sudo apt-get update
  - sudo apt-get install -y chromium-chromedriver
install:
  - pip install nose
  - pip install nose-pathmunge
  - pip install nose-htmloutput
  - pip install selenium
  - pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04 wxPython
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
script:
  - easyselenium/scripts/easy_selenium_cli.py --with-path /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode --logging-level=INFO -b gc
